

    
######################################################    
# Postgres Details
#######################################################
spring.datasource.url : jdbc:postgresql://localhost:5432/test?useUnicode=yes&characterEncoding=UTF-8
spring.datasource.username : postgres
spring.datasource.password : postgres

spring.jpa.hibernate.ddl-auto : update
spring.datasource.driverClass : org.postgresql.Driver
spring.jpa.database-platform : org.hibernate.dialect.PostgreSQLDialect

##### My Sql details ##########
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
#spring.datasource.username=username
#spring.datasource.password=password

#spring.jpa.hibernate.ddl-auto : update
#spring.datasource.driverClass : com.mysql.jdbc.Driver 
#spring.jpa.database-platform : org.hibernate.dialect.MySQLDialect

